version: '3'
x-zookeeper-common:
  &zookeeper-common
  image: confluentinc/cp-zookeeper:latest
  environment:
    &zookeeper-common-env
    ZOOKEEPER_CLIENT_PORT: 2181
    ZOOKEEPER_DATA_DIR: /var/lib/zookeeper/data
    ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
    ZOOKEEPER_SYNC_LIMIT: 5
    ZOOKEEPER_TICK_TIME: 2000

x-kafka-common:
  &kafka-common
  image: confluentinc/cp-kafka:latest
  environment:
    &kafka-common-env
    KAFKA_DEFAULT_REPLICATION_FACTOR: 3
    KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    KAFKA_LOG_DIRS: /var/lib/kafka/data
    KAFKA_LOG_RETENTION_HOURS: 168
    KAFKA_MIN_INSYNC_REPLICAS: 2
    KAFKA_NUM_PARTITIONS: 3
    KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
    KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 6000

services:
  zookeeper-1:
    <<: *zookeeper-common
    volumes:
      - zookeeper-data-1:/var/lib/zookeeper/data
    environment:
      <<: *zookeeper-common-env
      ZOOKEEPER_SERVER_ID: 1

  zookeeper-2:
    <<: *zookeeper-common
    volumes:
      - zookeeper-data-2:/var/lib/zookeeper/data
    environment:
      <<: *zookeeper-common-env
      ZOOKEEPER_SERVER_ID: 2

  zookeeper-3:
    <<: *zookeeper-common
    volumes:
      - zookeeper-data-3:/var/lib/zookeeper/data
    environment:
      <<: *zookeeper-common-env
      ZOOKEEPER_SERVER_ID: 3

  kafka-1:
    <<: *kafka-common
    depends_on:
      - zookeeper-1
    volumes:
      - kafka-data-1:/var/lib/kafka/data
    environment:
      <<: *kafka-common-env
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://kafka-1:29092

  kafka-2:
    <<: *kafka-common
    depends_on:
      - zookeeper-2
    volumes:
      - kafka-data-2:/var/lib/kafka/data
    environment:
      <<: *kafka-common-env
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://kafka-2:29092

  kafka-3:
    <<: *kafka-common
    depends_on:
      - zookeeper-3
    volumes:
      - kafka-data-3:/var/lib/kafka/data
    environment:
      <<: *kafka-common-env
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092,PLAINTEXT_HOST://kafka-3:29092

volumes:
  kafka-data-1:
  kafka-data-2:
  kafka-data-3:
  zookeeper-data-1:
  zookeeper-data-2:
  zookeeper-data-3:
